IsantePlus/openmrs-module-isanteplusreports

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/fullDataExports/numberVisitsByMonth.sql
**numberVisitsByMonth.sql report**
By our understanding, it should display a number of visits grouped by month and then grouped by location.
However, it was not grouped by location.
For example. In 2011-05 there were 2 encounters, one in location_id 896, and one in 1077.
The report was returning that both of the encounters were in location_id 1077.
**We've fixed it so it displays that one encounter was in location_id 896, one in 1077.**
=> Group by location in numberVisitsByMonth.sql report

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfChildrenWithNutritionalAssessment.sql
* Included exposed children and HIV+ children
* Removed a Pediatric Rx case from the numerator and the denominator
=> ITOS-311: Converted the pediatric 9. indicator from v2 to v3

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/retentionOfPatientsOnArt.sql
Changes:
- Numerator: instead of "pd.next_dispensation_date" use "drug order form completed on date X".
- Denominator: exclude discontinued instead of deceased, HIV+ Patients only
This indicator needs testing.
=> ITOS-289: Adjust Adult 1 Indicator to match latest specs

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfHivOnArtUndetectableViralLoadTest6Months.sql
When computing patients who have been on ART for 6months, changed the date filter to use the "endDate" instead of the "startDate" parameter
=> Health-Qual-Adult-16

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfHivOnArtViralLoadTest.sql
When computing patients who have been on ART for 6months, changed the date filter to use the endDate instead of the startDate parameter
=> Health-Qual-Adult-15

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfHivOnArtViralLoadTest6Months.sql
When computing patients who have been on ART for 6months, changed the date filter to use the endDate instead of the startDate parameter
=> Health-Qual-Adult-14

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfHivWomenUsingFamilyPlanning.sql
When getiing the denominator, changed the query to compute age based on the reporting 'endDate' instead of 'Now'
=> Health-Qual-Adult-11

api/src/main/java/org/openmrs/module/isanteplusreports/healthqual/util/RegisterAllHealthQualReports.java, api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/childrenRegularlyFollowedOnArt.sql
- When computing the numerator, removed the filter " AND pp.rx_or_prophy
= 138405" which seems to not have additional value
- To ensure consistency with other similar queries in the use of parameters, changed the date parameter from "startDate" to "currentDate"
- Also changed the corresponding report definition util method to
reflect the query parameter change.
- When computing the Numerator, Filtered Encounter Type to restrict (Paeds
Initial and follow-up encounters only)
---------------------
---------------------
>**Proportion of children regularly followed on ART**
> **_Numerator_**: Cumulative number of children on ART who have had at least one visit during the last 3 months.
> **_Calculation method_**: Pediatric HIV+ patients on ART excluding deceased, those who …
=> Health-Qual-Paed-1

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/childrenHivAndPlacedOnArt.sql
- When computing the denominator, added the Peads Initial and Followup
encounters to the query filter.
----
--
> **Proportion of children tested positive for HIV and placed on ART during the selected period.**
> **_Numerator_**: Number of HIV+ children placed on ART during the selected period.
> **_Calculation method_**: Pediatric HIV+ patients on ART excluding deceased, those who discontinued treatment, transfers and those who had a negative PCR result, who have had at least one visit (HIV First Pediatric Visit or Pediatric Follow-up or Pediatric Rx) during the selected period.
> **_Denominator_**: Number of children who were diagnosed with HIV and seen in
> the clinic during the selected period, excluding those who have suspended treatment, those who had a negative …
=> Health-Qual-Paed-2

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/pediatricHivAndReceivedCotrimoxazoleProphylaxis.sql
- When computing the denominator, Modified filter for excluding patients
older than 4 weeks and patients with negative PCR results after 18 Months
of Age
----
--
> **Proportion of children exposed to or infected with HIV who received cotrimoxazole prophylaxis during the selected period.**
> **_Numerator_**: Number of children exposed to and infected with HIV followed in clinic who are eligible for cotrimoxazole prophylaxis and received it during the reporting period.
> **_Calculation method_**: Pediatric HIV+ patients (4 or more weeks old) excluding deceased, those who discontinued treatment, transfers and those who had a negative PCR result after 18 months of age, who have had at least one visit (HIV First Pediatric Visit or Pediatric Follow-up or Pediatric Rx) …
=> Health-Qual-Paed-3

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/pediatricBenefitedFromAnAdherence.sql
- When computing the denominator, added the peads Initial and followup
encounters to the query filter
----
--
> **Proportion of HIV+ children on ART who have had an adherence evaluation during the last 3 months.**
> **_Numerator_** : Number of HIV+ children on ART who have had an adherence evaluation (a pill count or completed questionnaire saved to their chart) in the last 3 months.
> **_Calculation method_**: Pediatric HIV+ patients on ART excluding deceased, those who discontinued treatment, transfers and those who had a negative PCR result, who have had at least one visit (HIV First Pediatric Visit or Pediatric Follow-up or Pediatric Rx) during the last three months and who benefited from an adherence evaluation. 
> **_Denominator_**: Number of children on ART who …
=> Health-Qual-Paed-4

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/childrenOnArtWhoAreConsideredAdherent.sql
- When computing the denominator, added the peads Initial and followup
encounter types to the query filter
----
--
> **Proportion of HIV+ children on ART who are considered adherent**
> **_Numerator_**: Cumulative number of pediatric patients enrolled in ART for more than 3 months who have an adherence level ≥ 95%.
> **_Calculation method_**: Pediatric HIV+ patients on ART excluding deceased, those who discontinued treatment, transfers and those who had a negative PCR result, who have had at least one visit (HIV First Pediatric Visit or Pediatric Follow-up or Pediatric Rx) during the last three months and have an adherence level ≥ 905%. See Figure 15 in the Adult section.
> **_Denominator_**: Cumulative number of pediatric patients enrolled in ART for more than 3 …
=> Health-Qual-Paed-5

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfHIVChildrenTestedForTB.sql
- When computing the denominator, changed the 6Month age calculation's effective date from the parameter "endDate" to Visits Table's "visit_date" column
----
--
> **Proportion of HIV+ children tested for TB at enrolment during the selected period**
> **_Numerator_**: Number of children 6 months of age and older who are assessed for TB at enrollment during the selected period.
> **_Calculation method_**: Pediatric HIV+ patients older than 6 months of age excluding deceased, those who discontinued treatment, transfers and those who had a negative PCR result, who have had an HIV First Pediatric Visit with the TB section completed indicating a non-null result during the selected period.
> **_Denominator_**: Number of HIV-infected children age 6-months and older who are …
=> Health-Qual-Paed-6

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfHIVChildrenOlderThanOneYearOfAgeReceivedINH.sql
- When computing the denominator, changed the age calculation effective date from parameter "endDate" to Visit's table "visit_date" column
----
--
> **Proportion of eligible (TB-negative) HIV+ children older than 1 year of age who received INH chemoprophylaxis during the selected period.**
> **_Numerator_**: Number of HIV+ children older than 1 year of age enrolled at the clinic during the selected period who received INH prophylaxis.
> **_Calculation method_**: Pediatric HIV+ patients older than 1 year of age excluding deceased, those who discontinued treatment, transfers, those who had a negative PCR result, and those who have active TB who have had received INH prophylaxis during the selected period
> (HIV First Pediatric Visit or Pediatric Follow-up AND Pediatric …
=> Health-Qual-Paed-7

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/pediatricReceivedPcrTest.sql
- When computing the denominator, added criteria for PCR eligibility
----
--
> **Proportion of HIV-exposed infants between 4 weeks old and 18 months old who have received a PCR test during the selected period**
> **_Numerator_**: Number of HIV-exposed infants between 4 weeks old and 18 months old who have received a PCR test at the clinic during the selected period.
> **_Calculation method_**: HIV-exposed children between 4 weeks old and 18 months old excluding discontinued cases, deceased, and transfers, who have had at least one visit (HIV First Pediatric Visit or Pediatric Follow-up or Pediatric Rx) and who had a PCR test done during the selected period.
> **_Denominator_**: Number of HIV-exposed infants between 4 weeks old and 18 months old who were seen at the …
=> Health-Qual-Paed-12

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/pediatricNegativePcrTest.sql
- When computing the denominator, changed the age calculation effective date from parameter "endDate" to Visits Table "visit_date" column
----
--
> **Proportion of HIV-exposed infants who had a negative PCR test result during the selected period.**
> **_Numerator_**: Number of HIV-exposed infants between 4 weeks and 18 months old whose most recent PCR test result is negative.
> **_Calculation method_**: HIV-exposed children between 4 weeks old and 18 months old excluding discontinued cases, deceased, and transfers, who have had at least one visit (HIV First Pediatric Visit or Pediatric Follow-up or Pediatric Rx) and whose latest PCR test was negative during the selected period.
> **_Denominator_**: Number of HIV-exposed infants between 4 weeks and 18 months old who …
=> Health-Qual-Paed-13

api/src/main/java/org/openmrs/module/isanteplusreports/healthqual/HealthQualManager.java, api/src/main/java/org/openmrs/module/isanteplusreports/healthqual/util/HealthQualReportsConstants.java, api/src/main/java/org/openmrs/module/isanteplusreports/healthqual/util/RegisterAllHealthQualReports.java, api/src/main/resources/messages.properties, api/src/main/resources/messages_es.properties, api/src/main/resources/messages_fr.properties, api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/earlyInfantDiagnosis.sql, messages.properties, messages_es.properties, messages_fr.properties
Added the Early Infant Diagnosis Indicator to the Health Qual report
----
--
**Numerator**: Number of children between 4 weeks- and 1 year-old, and those between 12 and 18 months-old who had an early infant diagnosis via PCR test at any time before the close of the reporting period.
**Calculation method**: Pediatric patient between 4 weeks and 12 months of age, and those between 12 and 18 months of age who have had a HIV First Pediatric Visit or Pediatric Follow-up or Pediatric Rx and who have had a PCR test during the selected period. 
**Denominator**: Number of children between 4 weeks- and 1 year-old, and those between 12 and 18 months-old who were seen in the clinic during the reporting period and had a positive rapid HIV test result. 
**Calculation method**: …
=> Health-Qual-Paed-14

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfHIVChildrenYoungerThanOneYearOfAgeReceivedINH.sql
When computing the denominator:
- changed the age calculation effective date from reporting "endDate" to the "visit_date"
- corrected the query to exclude Active TB patients (as per the indicator definition)
- Added the check for HIV exposed infants
----
--
**Proportion of HIV-exposed or infected children younger than 1 year of age who received INH chemoprophylaxis during the selected period.**
**_Numerator_**: Number of HIV-exposed or infected children younger than 1 year of age who had contact with active TB and were placed on INH prophylaxis.
**_Calculation method_**: Eligible pediatric HIV+ patients or HIV-exposed children less than 1 year of age excluding deceased, those who discontinued treatment, transfers, and those who have active TB who received INH …
=> Health-Qual-Paed-8

api/src/main/resources/org/openmrs/module/isanteplusreports/sql/healthQualReports/proportionOfChildrenWithNutritionalAssessment.sql
When computing the denominator, added the peads Initial and followup
encounter types to the query filter
----
--
**Proportion of HIV-exposed or HIV+ children who have had a nutritional assessment during the selected period.**
**_Numerator_**: Number of HIV-exposed or infected children who have the necessary data to evaluate their nutritional status (weight and height or MUAC and head circumference) saved in their chart during the selected period.
**_Calculation method_**: HIV-exposed children or pediatric HIV+ patients excluding deceased, those who discontinued treatment, transfers and those who had a negative PCR result, have had at least one visit (HIV First
Pediatric Visit or Pediatric Follow-up) and who have had a nutritional assessment completed during the …
=> Health-Qual-paed-9

api/src/main/java/org/openmrs/module/isanteplusreports/healthqual/util/HealthQualReportsConstants.java
Corrected typo on the naming of an SQL resource file. @ckemar please merge
=> Typo on SQL resource file name
